"""Bulk-import cleaned OSM HCMC locations into the SQLite DB.

The cleaned CSV (osm_hcmc_locations_cleaned.csv) is generated by clean_csv.py.
It contains ~5,000 high-quality POIs filtered from the original 14,340 entries.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from streamlit_app.data.locations_db import add_many_locations, get_location_count

csv_path = Path(__file__).parent.parent / "data" / "osm_hcmc_locations_cleaned.csv"

print(f"Loading {csv_path}...")
rows = []
with open(csv_path, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        try:
            rows.append({
                "name": row["name"].strip(),
                "lat": float(row["lat"]),
                "lon": float(row["lon"]),
                "category": row.get("category", "other") or "other",
                "address": row.get("address", "").strip(),
                "osm_id": row.get("osm_id", ""),
                "source": "osm",
            })
        except (ValueError, KeyError):
            continue

before = get_location_count()
print(f"DB had {before} locations. Importing {len(rows)}...")

count = add_many_locations(rows)
after = get_location_count()

print(f"Imported {count} rows.")
print(f"DB now has {after} locations (+{after - before} new).")
